Updated stream.sh to take a parameter to choose a stream, and supervisor.conf acccordingly

diff --git a/stream.sh.in b/stream.sh.in
--- a/stream.sh.in
+++ b/stream.sh.in
@@ -1,9 +1,11 @@
 #!/bin/bash
 set -e
 function USAGE {
-    echo "Usage: stream.sh [-h] n"
+    echo "Usage: stream.sh [-h] [lr] [hr]"
     echo " -h    This help text."
-    echo " n number of streams to create, either 1 or 2."
+    echo " lr    create the low-res stream "
+    echo " hr    create the hi-res stream "
+    echo " Either hr or lr must be specified (or both)"
 }
 
 function INIT {
@@ -45,22 +47,22 @@ then
     exit 1
 fi
 
-N_STREAMS=$@
-
-CMD="ffmpeg -f @MUXER@ -s @DEFAULT_FULL_RESOLUTION@ -r 30 -i @INPUT_DEVICE@"
-STR1="-f hls -hls_time 0.35 -hls_allow_cache 0 -hls_flags temp_file+delete_segments+independent_segments -hls_delete_threshold 1 -hls_list_size 6 -c:v libx264 -b:v 7000k -maxrate 10000k -bufsize 10000k -crf 18 -flags +cgop+low_delay+qscale -r 3 -g 3 -refs 1 -strict normal -level 4.2 -profile:v high -preset ultrafast -tune zerolatency -pix_fmt yuv420p @WWW_DIR@/hls/stream_hr.m3u8"
-STR2="-f hls -hls_time 0.35 -hls_allow_cache 0 -hls_flags temp_file+delete_segments+independent_segments -hls_delete_threshold 1 -hls_list_size 6 -c:v libx264 -s 384x216 -b:v 2000k -maxrate 5000k -bufsize 4000k -crf 18 -flags +cgop+low_delay+qscale -r 20 -g 20 -refs 1 -strict normal -level 4.2 -profile:v high -preset ultrafast -tune zerolatency -pix_fmt yuv420p  @WWW_DIR@/hls/stream_lr.m3u8"
-if [ ${N_STREAMS} == 1 ]
-then
-    echo "Streaming to @WWW_DIR@/hls/stream_hr.m3u8"
-    INIT
-    eval ${CMD} ${STR1}
-elif [ ${N_STREAMS} == 2 ]
-then
-    echo "Streaming to @WWW_DIR@/hls/stream_hr.m3u8 and @WWW_DIR@/hls/stream_lr.m3u8"
-    INIT
-    eval ${CMD} ${STR1} ${STR2}
-else
-    echo "Number of streams has to be 1 or 2, given ${N_STREAMS}"
-    exit 1
-fi
+CMD=ffmpeg
+ARGS=(-f @MUXER@ -s @DEFAULT_FULL_RESOLUTION@ -r 30 -i @INPUT_DEVICE@) #-threads 2
+for var in "$@"
+do
+    case ${var} in
+        hr ) #add hi-res stream
+            ARGS+=(-f hls -hls_time 0.35 -hls_allow_cache 0 -hls_flags temp_file+delete_segments+independent_segments -hls_delete_threshold 1 -hls_list_size 6 -c:v libx264 -b:v 7000k -maxrate 10000k -bufsize 10000k -crf 18 -flags +cgop+low_delay+qscale -r 3 -g 3 -refs 1 -strict normal -level 4.2 -profile:v high -preset ultrafast -tune zerolatency -pix_fmt yuv420p @WWW_DIR@/hls/stream_hr.m3u8)
+            ;;
+        lr ) #add lo-res stream
+            ARGS+=(-f hls -hls_time 0.35 -hls_allow_cache 0 -hls_flags temp_file+delete_segments+independent_segments -hls_delete_threshold 1 -hls_list_size 6 -c:v libx264 -s 384x216 -b:v 2000k -maxrate 5000k -bufsize 4000k -crf 18 -flags +cgop+low_delay+qscale -r 20 -g 20 -refs 1 -strict normal -level 4.2 -profile:v high -preset ultrafast -tune zerolatency -pix_fmt yuv420p @WWW_DIR@/hls/stream_lr.m3u8)
+            ;;
+        * )
+            echo "Invalid stream: ${var}" 1>&2
+            USAGE
+            exit 1
+            ;;
+    esac
+done
+eval $CMD ${ARGS[@]} 
